#image: frekele/gradle:3.4.1-jdk7
image: skobow/docker-gradle-git
stages:
  - build
before_script:
  - echo `pwd` # debug
  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
#  - export GRADLE_USER_HOME=`pwd`/.gradle
build:
  stage: build
  script:
    - gradle clean build
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    - master
after_script:
  - echo "End CI"