##################################################
#
# Environment
#
##################################################
language: groovy
jdk:
  - openjdk8
os:
  - linux



##################################################
#
# CACHE
#
##################################################
before_cache:
  - echo "################################################## START CACHE"
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
after_cache:
  - echo "################################################## FINISH CACHE"



##################################################
#
# SCRIPT
#
##################################################
script:
  - ./gradlew clean build
  - export RELEASE_PKG_FILE=$(ls build/distributions/*.zip)
  - echo "# Zip File => $RELEASE_PKG_FILE"



##################################################
#
# DEPLOY
#
##################################################
before_deploy:
  - export RELEASE_PKG_FILE=$(ls build/distributions/*.zip)
  - echo "################################################## START DEPLOY "
  - echo "# Deploying $RELEASE_PKG_FILE to GitHsub releases"
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file: "build/distributions/*.zip"
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
    repo: avaj-java/installer-maker
    all_branches: true
after_deploy:
  - echo "################################################## FINISH DEPLOY"



##################################################
#
# SUCCESS
#
##################################################
after_success:
  - ./gradlew jacocoTestReport coveralls
