language: groovy

jdk:
  - oraclejdk8

os:
  - linux

branches:
  only:
    - master

script:
  - gradle clean build
  
deploy:
  provider: releases
  api_key:
    secure: 2a26f5e51a9e7fe58c6c4dbaf735129b6755fe1e
  file: build/libs/*
  skip_cleanup: true
  on:
    tags: false
